### Introduction to Numerical Python (NumPy)

![alt text](https://images.unsplash.com/photo-1517976487492-5750f3195933?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=5ab4ea4fd87e2144a8662bee0164010d&auto=format&fit=crop&w=500&q=60)

package ในตำนานที่ใช้ในการทำ computation ใน Python ใครอยากทำ data analysis ใน Python ต้องใช้ numpy ทุกคนเลย

ทำไม numpy ถึงฮอทขนาดนี้?
- numpy เร็วมาก **เร็วเหมือนจรวด**
- numpy ใช้ง่ายมากเช่นกัน

tutorial นี้เราจะแนะนำการใช้งาน numpy เบื้องต้น เริ่มจากการ import มันเข้า notebook ของเราก่อน

```
import numpy as np
```

In [0]:
# import numpy into our notebook
import numpy as np

In [0]:
# create normal list
my_list = [1,2,3,4,5,6,7,8,9,10]

print(type(my_list))

เราสามารถเปลี่ยน list ธรรมดาให้กลายเป็น np.ndarray ด้วยฟังชั่น

```
np.array(list)
```

In [0]:
# create numpy array
my_arr = np.array(my_list)

print(type(my_arr))
print(my_arr)

### basic statistics with numpy

เวลาจะเรียกใช้งานฟังชั่นของ numpy เราสามารถพิมพ์แบบนี้ได้เลย
```
np._____( )
```
โดยฟังชั่นสถิติหลักๆของ numpy มีดังนี้
- np.mean()
- np.median()
- np.sum()
- np.max()
- np.min()
- np.std()

In [0]:
my_arr

In [0]:
# หาค่าเฉลี่ย mean
np.mean(my_arr)

In [0]:
print("mean: " + str(np.mean(my_arr)))
print("median: " + str(np.median(my_arr)))
print("max: " + str(np.max(my_arr)))
print("min: " + str(np.min(my_arr)))
print("standard deviation: " + str(np.std(my_arr)))
print("variance: " + str(np.var(my_arr)))
print("sum: " + str(np.sum(my_arr)))

### ง่ายอะไรเบอร์นี้ !!

มาลองสร้าง array ง่ายๆกันด้วยฟังชั่น ```np.arange()```

ใช้เหมือนกับฟังชั่น ```range()``` ที่เราเรียนมาในบทก่อนหน้านี้เลย

In [0]:
x = np.arange(20)

print(x)

In [0]:
y = np.arange(5, 16, 2)

print(y)

### เราสามารถตรวจสอบค่าใน array ได้ง่ายๆด้วย basic boolean

In [0]:
y = np.arange(5, 30, 3)

print(y)

In [0]:
y <= 20

In [0]:
y == 23

In [0]:
# slice ด้วย boolean
y[y <= 20]

In [0]:
# slice ค่าที่มากกว่า 20 ขึ้นไป
y[y > 20]

### เราสามารถบวก ลบ คุณ หาร array ได้ปกติเลย

In [0]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])

In [0]:
x * 2

In [0]:
x + y

In [0]:
y + 100

In [0]:
x = np.array([1,2,3])
y = np.array([4,5,6])

print(x+y)

### two-dimensional array

In [0]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(arr)

In [35]:
type(np.array([ [1,2], [3,4]  ]))

numpy.ndarray

In [0]:
print(np.mean(arr))
print(np.sum(arr))

In [36]:
# print arr
print(arr)
print("")

# axis = 1
print("sum every row")
print(np.sum(arr, axis=1))

# axus = 0
print("")
print("sum every column")
print(np.sum(arr, axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

sum every row
[ 6 15 24]

sum every column
[12 15 18]


### Summary

![alt text](https://images.unsplash.com/photo-1531482615713-2afd69097998?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=3a748e7b25651211d3092e562247c860&auto=format&fit=crop&w=500&q=60)

และนี่คือการทำงานด้วย numpy ในระดับเบื้องต้น

อย่าลืม ```import numpy as np``` ก่อนที่จะใช้ฟังชั่นนะครับ

สำหรับเพื่อนๆที่อยากมาทางสาย data science การเขียน numpy ให้คล่อง สำคัญมากจริงๆ package เดียวทำได้แทบจะทุก computation เลย

EP20 ที่เราจะสอน pandas ก็เป็น package ที่ใช้ความสามารถของ numpy เหมือนกัน